### ISSUE TITLE
Getting a "UriParseFailure"

### ISSUE THREAD

**Issue by dwaynebradley** [encabulators/natsclient#2]
I currently have NATS deployed in a K8S cluster via the following Helm chart:

https://hub.helm.sh/charts/bitnami/nats (NATS 2.0 version)

I have the following settings changed from the defaults:

client.service.type = NodePort
client.service.nodePort = 32224

When I try to connect using `nats://<my-dns-name-here>:32224`, this is the error I'm seeing:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: UriParseFailure, description: Some("URI parse failure: relative URL without a base") }', src/libcore/result.rs:997:5
```

If I use a web browser to go to `http://<my-dns-name-here>:32224`, I'm seeing the following:

```
INFO {"server_id":"NAMOPNRV24QV4LVYZ7P7HHF3OH3TNEKG3YWTGO7S6VSL5A6UZRUYVE5F","version":"2.0.0","proto":1,"go":"go1.11.10","host":"0.0.0.0","port":4222,"max_payload":1048576,"client_id":14,"connect_urls":["10.42.1.8:4222","10.42.6.65:4222","10.42.0.9:4222"]} 
-ERR 'Unknown Protocol Operation'
```

Just as an additional check to make sure that the cluster is working, I am able to use the [go-nats](https://github.com/nats-io/go-nats) example program `nats-sub` using the same URL as above and connect successfully...and see data flowing from other apps publishing data.

Just FYI...this NATS deployment is private, behind a firewall. <my-dns-name-here> can't be accessed publicly but **can** reach out.

**Comment by tupshin** [comment]
The problem is due to the connect_urls in the server response having the form "1.2.3.4:5678". These are technically uris but not urls and the url parser blows up on them. I'm not sure if the server is operating within spec here but either way the client could be more robust.

In 
`fn parse_nats_uri` in protocol.rs, a special case could be made to check for the address:port format and either prepend "nats://" to it before parsing it as a URL, or else special casing the URI generation in that case

**Comment by derekcollison** [comment]
So does the parse require a scheme?

**Comment by tupshin** [comment]
Yes, it appears that the URL parsing library requires a scheme, or at least it does in this case. No super elegant solution comes to mind, but a decent possibility is
1) doing a pre-parse check for "contains ://" 
2) and if it doesn't, prepend "nats://" prior to parsing

**Comment by derekcollison** [comment]
If it works ;)

**Comment by autodidaddict** [comment]
I apologize for not seeing this conversation earlier. Github _should_ e-mail me to let me know someone created an issue and a PR but it's not. Feel free to at-me/tag me/throw flaming poo at my doorstep if I appear unresponsive.
