### ISSUE TITLE
Master branch doesn't compile - ed25519-dalek v1.0.0-pre.3

### ISSUE THREAD

**Issue by dawid-nowak** [encabulators/natsclient#4]
Hey;
I just pulled the master branch and it doesn't compile
![image](https://user-images.githubusercontent.com/25728428/70476166-12402400-1ace-11ea-91b3-e44dc286c333.png)

Could you confirm?

**Comment by dawid-nowak** [comment]
i think you will need to bump nkeys dependency to "0.0.8"

**Comment by ZoroSC** [comment]
I can confirm I am also getting this error.

**Comment by dawid-nowak** [comment]
closed 
https://github.com/encabulators/natsclient/commit/156bff4e2385ac75c17ee3680bda39df4cc772b1
